#!/bin/bash
JSON="$(rclone lsjson nebolle_gdrive: | jq ".[].Name")"
NAME="$(echo "$JSON" | fzf)"
PNAME=$(echo $NAME | cut -d "]" -f2 | cut -d "[" -f1 | awk '{$1=$1};1')
echo "rclone copy -P nebolle_gdrive:$NAME" ./\"$PNAME\" | $SHELL
