#!/usr/bin/env bash

rofi_command="rofi -theme ~/.config/rofi/themes/sed.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# options
shutdown="shutdown"
reboot="reboot"
lock="lock"
suspend="suspend"
hibernate="hibernate"
logout="logout"
game="game"
caffeine="caffeine"

# variable passed to rofi
options="$lock\n$logout\n$shutdown\n$suspend\n$hibernate\n$reboot\n$game"
# options="$lock\n$logout\n$shutdown\n$suspend\n$hibernate\n$reboot\n$game\n$caffeine"

chosen="$(echo -e "$options" | $rofi_command -p "神  $uptime:" -dmenu)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
		$HOME/.scripts/lockscreen
        ;;
    $suspend)
        # amixer set Master mute
        systemctl suspend
        ;;
    $hibernate)
        systemctl hibernate
        ;;
    $logout)
		xdotool key Super_L+Alt_L+q
		# $HOME/.config/bspwm/bspwm_quit
        # qtile cmd-obj -o cmd -f shutdown
        ;;
	$game)
		if [ -z $(pidof picom) ]
		then
			nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }" &
			picom --experimental-backends &
			dunstify 'game mode off'
		else
			nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = Off }" &
			killall picom &
			dunstify 'game mode on'
		fi
        ;;
	$caffeine)
		if [ $(xset q | grep timeout | sed 's@^[^0-9]*\([0-9]\+\).*@\1@') -eq "0" ]
		then
			xset s 600
			dunstify 'caffeine off'
		else
			xset s 10000000
			dunstify 'caffeine on'
		fi
        ;;
esac
